### ISSUE TITLE
Infinite load on Win10

### ISSUE THREAD

**Issue by Limeony** [Naxesss/MapsetVerifier#12]
Infinite load on Win10
MapsetVerifierBackend do nothing when running it

**Comment by Naxesss** [comment]
Going to need some more info, so do this:

In `/Mapset Verifier/resources/app/api/win-x86` create folders `/resources/app/checks` and copy paste `MapsetChecks.dll` from `/Mapset Verifier/resources/app/checks` into it. So like this:

![](https://i.imgur.com/Um9XD7E.png)

Now run `/Mapset Verifier/resources/app/api/win-x86/MapsetVerifierBackend.exe`. It should explain what the problem is, but it will probably instantly close afterwards, so take a screenshot of it before it closes (could take a few tries), then send it here.

If it doesn't run at all, try whitelisting it in any anti-virus you may have, they usually false positive on this exe (preventing it from running), may even solve the issue if that is what's happening.

**Comment by Limeony** [comment]
I did it but nothing happens, cmd was still blank, i doesnt even have an antivirus.
Afterwards i decided to reinstall program and for some reason it started to work, i really dont know the reason behind this.
Thanks for help and sorry for troubling.
