### ISSUE TITLE
Clicking of extra icons causes app freezes and crashes afterwards

### ISSUE THREAD

**Issue by Ztumpie905509** [Naxesss/MapsetVerifier#14]
Extra rows of icon are found.
![My map which got issues](https://user-images.githubusercontent.com/48085506/122029020-22da0480-cdff-11eb-831f-dbdb3d5ac489.png)

It should be like this :

Random ranked map
![Random Ranked map](https://user-images.githubusercontent.com/48085506/122029031-24a3c800-cdff-11eb-9fbf-fa75a135d5b9.png)
Random loved map
![Random Loved map](https://user-images.githubusercontent.com/48085506/122029034-253c5e80-cdff-11eb-8cf8-38c7fe46bb94.png)

Besides, when I click any icons in my map, the app freezes and crashes.

If you need my map to test here's the link : https://osu.ppy.sh/beatmapsets/1398887#osu/3016977

**Comment by Naxesss** [comment]
This happens because there are too many issues to the point where the javascript processing crashes. Specifically your Hitsound(s) difficulty has an absurd amount of problems. Most things reliant on said javascript will stop functioning as a result, mainly showing/hiding of issues and categories. I've tried a few things to fix this issue in the past but without much luck.

In your case you can temporarily move out the hitsound difficulty and you'll see that MV runs properly again, so would recommend you do that.

**Comment by Ztumpie905509** [comment]
ok, thank you for the solution to this, removed the hitsounds diff and problem are solved.
