### ISSUE TITLE
Mapset Verifier is not able to populate the map list if osu! is on External HDD

### ISSUE THREAD

**Issue by Skubers** [Naxesss/MapsetVerifier#18]
Summary:
I've got my osu! folder on external HDD and setting up the folder in-app to the Songs folder on my external HDD doesn't populate the maplist
![image](https://user-images.githubusercontent.com/82095491/144834564-42b64459-c717-4b33-9146-f112407d9bde.png)
![image](https://user-images.githubusercontent.com/82095491/144834608-90eefdd2-a6b1-40d6-8cb7-027155304bd0.png)

Repro Rate:
Mapset Verifier 1.8.2 on 21H1 (19043.1348) - 5/5

Repro Steps:
1. Install the app
2. Make sure your osu! folder is on an External HDD
3. Select a Songs folder in-app
4. Observe the issue as the maplist doesn't populate

Expected Results:
Maplist populates and user is able to pick a map from it

Actual Results:
Maplist doesn't populate with maps

**Comment by Naxesss** [comment]
When you say "External HDD", do you mean connected through USB? I actually do not have an HDD myself so this is a little difficult for me to reproduce. I've asked around and only found people who use SATA HDDs, for which loading maps works fine.

I'd suggest trying the following things, which may give us more info on what the issue is:
- Open MV -> Go to settings (top right cogwheel) -> Click "Open externals folder" -> Have a look at the settings.ini file and ensure the "song-folder-path" value is correctly pointing at your HDD. Mine looks like this for reference:
![image](https://user-images.githubusercontent.com/30292137/145220509-223882dc-d30e-4fd6-9bc7-77ce1123c8a0.png)
- Open MV -> Ctrl + Shift + I (opens the inspect window) -> Click on the "Console" tab -> See if there are any errors that may be related to maps not loading (e.g. some folder/file not being found).

**Comment by Skubers** [comment]
Yep, I've meant a HDD connected through USB, and yup, after checking in the Inspector, I found this:
![image](https://user-images.githubusercontent.com/82095491/145245192-92208d80-17e2-4cf7-8322-5adf7e5f1a83.png)

I ran the MV as an Administrator and it started working fine :) Thanks for helping me out!
There is no info that you should run it as an Administrator though, so you should probably address that some way :x

**Comment by Naxesss** [comment]
No problem, glad you solved it!
