### ISSUE TITLE
Inconsistencies in snapping detection too sensitive?

### ISSUE THREAD

**Issue by abraker95** [Naxesss/MapsetVerifier#2]
![](https://i.imgur.com/WcJowP5.png)
Got this on [this  beatmap](https://osu.ppy.sh/beatmapsets/827849#mania/1734602), but there are more than two of such snapped hitobjects

**Comment by Naxesss** [comment]
can only see those two on 1/6, where are the other ones you mentioned?

**Comment by abraker95** [comment]
ooo I see now. It doesn't see that the notes were shifted by 1/12 snapping. Most of those short hold notes start at 1/6 and end 1/12 except those two which start 1/12 and end 1/6.

**Comment by Naxesss** [comment]
ye you have a lot of lns ending on 1/12 but only those two are 1/6. Check doesn't really care about how long the sliders are, only which ticks they exist on. Reason why it's sensitive and easily does false positives is because it's commonly something people miss and maps need to be dqed for, not really sure if I could make this less sensitive while still being as safe (stuff like shifting by 1/16 is something it'd want to catch, for example)

**Comment by abraker95** [comment]
Well ok, I guess there is no issue after all.
