### ISSUE TITLE
Couldn't work on Windows 7

### ISSUE THREAD

**Issue by int100** [Naxesss/MapsetVerifier#3]
When I opened any mapsets on Windows 7, there were no responses to loading. 
![Windows 7](https://user-images.githubusercontent.com/17942244/62510378-68ac0600-b841-11e9-84c1-647bda0e85ec.png)

But when I used it on Windows 10, it could work well.
![Windows 10](https://user-images.githubusercontent.com/17942244/62510430-92652d00-b841-11e9-8e21-9610c80875bc.png)

**Comment by Naxesss** [comment]
ok so in windows 7, go to the install location
Mapset Verifier/resources/app/api/MapsetVerifierBackend.exe
run it and screenshot what it says, should print a stack trace if it crashes

guessing it's that because loading is normally taken care of by the backend but if it's dead nothing will show up like in the first screenshot

**Comment by int100** [comment]
Thanks for replying, I've solved the problem.

![problem](https://user-images.githubusercontent.com/17942244/62524648-935d8500-b868-11e9-9c17-b1ea05a0883b.png)

.Net Core needs KB2533623 to run. After installing it, the program works fine.
