### ISSUE TITLE
Lowest expert diff

### ISSUE THREAD

**Issue by dudehacker** [Naxesss/MapsetVerifier#4]
It is detecting expert as lowest diff. Which doesn't make any sense.

Is it because of the hitsound diff?

https://i.imgur.com/30NNHZL.png

map with issue: https://osu.ppy.sh/beatmapsets/914868#mania/1933299

**Comment by Naxesss** [comment]
that's just because mania doesn't have sr support (it's changing soon anyway so implementing the current seems kinda like a waste), current method pretty much just guesses by diff name - if it can't guess it just puts expert hence order is out of wack and that issue

what I could do is order by: name > sr > object density in that order, should partly solve this, usually lowest diff has least objects no matter the mode. It'll still mark everything as expert but at least you can change the lowest diff to the appropriate diff level and problems related to that will disappear

but yeah this issue will still be a thing because if it can't find the diff level reasonably from diff name or sr I don't think it should guess from factors like object density, will probably be super inaccurate
