### ISSUE TITLE
Hardware Accel

### ISSUE THREAD

**Issue by VINXIS** [Naxesss/MapsetVerifier#7]
Would be nice to have a Hardware Acceleration / GPU option so that it could possibly get through the map and toggle between difficulties in `Checks` mode

**Comment by Naxesss** [comment]
Went over things in discord; performance issue when toggling between difficulties in `Checks` is due to poor optimization in issue filtering (see `updateIssueVisibility` in `script.js` if curious). I've tried to mitigate this in the past, but haven't had much success. Don't think any GPU acceleration can save that (and electron seems to already use the GPU where possible).

Will probably end up overhauling this part at some point, but for now it's probably acceptable as it mostly only impacts long/big mapsets noticeably.
